import productPreview1 from '../../../assets/images/products/product-1.png';
import productPreview2 from '../../../assets/images/products/product-2.png';
import { IProductData } from '../../../store/reducer/products/products.model';

export const sliderProductsMock: IProductData[] = [
	{
		id: 'id-1',
		preview: productPreview1,
		name: 'Нож Лиса',
		price: 23217,
		href: '#',
		desc: '',
		category: ['Орех', 'Алюминий'],
		countComments: 12,
		size: '95х18',
	},
	{
		id: 'id-2',
		preview: productPreview2,
		name: 'Нож Лиса',
		price: 23217,
		href: '#',
		desc: '',
		category: ['Орех', 'Алюминий'],
		countComments: 12,
		size: '95х18',
	},
	{
		id: 'id-3',
		preview: productPreview1,
		name: 'Нож Лиса',
		price: 23217,
		href: '#',
		desc: '',
		category: ['Орех', 'Алюминий'],
		countComments: 12,
		size: '95х18',
	},
	{
		id: 'id-4',
		preview: productPreview2,
		name: 'Нож Лиса',
		price: 23217,
		href: '#',
		desc: '',
		category: ['Орех', 'Алюминий'],
		countComments: 12,
		size: '95х18',
	},
	{
		id: 'id-5',
		preview: productPreview1,
		name: 'Нож Лиса',
		price: 23217,
		href: '#',
		desc: '',
		category: ['Орех', 'Алюминий'],
		countComments: 12,
		size: '95х18',
	},
	{
		id: 'id-6',
		preview: productPreview2,
		name: 'Нож Лиса',
		price: 23217,
		href: '#',
		desc: '',
		category: ['Орех', 'Алюминий'],
		countComments: 12,
		size: '95х18',
	},
	{
		id: 'id-11',
		preview: productPreview1,
		name: 'Нож Лиса',
		price: 23217,
		href: '#',
		desc: '',
		category: ['Орех', 'Алюминий'],
		countComments: 12,
		size: '95х18',
	},
	{
		id: 'id-22',
		preview: productPreview2,
		name: 'Нож Лиса',
		price: 23217,
		href: '#',
		desc: '',
		category: ['Орех', 'Алюминий'],
		countComments: 12,
		size: '95х18',
	},
	{
		id: 'id-33',
		preview: productPreview1,
		name: 'Нож Лиса',
		price: 23217,
		href: '#',
		desc: '',
		category: ['Орех', 'Алюминий'],
		countComments: 12,
		size: '95х18',
	},
	{
		id: 'id-44',
		preview: productPreview2,
		name: 'Нож Лиса',
		price: 23217,
		href: '#',
		desc: '',
		category: ['Орех', 'Алюминий'],
		countComments: 12,
		size: '95х18',
	},
	{
		id: 'id-55',
		preview: productPreview1,
		name: 'Нож Лиса',
		price: 23217,
		href: '#',
		desc: '',
		category: ['Орех', 'Алюминий'],
		countComments: 12,
		size: '95х18',
	},
	{
		id: 'id-66',
		preview: productPreview2,
		name: 'Нож Лиса',
		price: 23217,
		href: '#',
		desc: '',
		category: ['Орех', 'Алюминий'],
		countComments: 12,
		size: '95х18',
	},
];
